export enum FuncRetEnum {
  USERNAME_EMPTY,
  USER_NOT_EXISTS,
  USER_ALREADY_EXISTS,
  ROOMNAME_EMPTY,
  ROOM_NOT_EXISTS,
  ROOM_ALREADY_EXISTS,
  ALREADY_IN_A_ROOM,
  NOT_IN_A_ROOM,
  OK,
  MALFORMED_REQUEST
}
