export enum ResponseEnum {
  USERNAME_EMPTY,
  USERNAME_TOO_LONG,
  USER_NOT_EXISTS,
  USER_ALREADY_EXISTS,
  USER_NOT_ADMIN,
  ROOMNAME_EMPTY,
  ROOMNAME_TOO_LONG,
  ROOM_NOT_EXISTS,
  ROOM_ALREADY_EXISTS,
  ALREADY_IN_A_ROOM,
  NOT_IN_A_ROOM,
  OK,
  MALFORMED_REQUEST
}
